# Generated by Django 6.0.4 on 2026-04-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.IntegerField(help_text='Number of times the patient has been pregnant')),
                ('glucose', models.FloatField(help_text='Plasma glucose concentration (mg/dL) from a 2-hour oral glucose tolerance test')),
                ('blood_pressure', models.FloatField(help_text='Diastolic blood pressure (mm Hg)')),
                ('skin_thickness', models.FloatField(help_text='Triceps skin fold thickness (mm)')),
                ('insulin', models.FloatField(help_text='2-hour serum insulin (μU/mL)')),
                ('bmi', models.FloatField(help_text='Body mass index (weight in kg / height in m²)')),
                ('diabetes_pedigree', models.FloatField(help_text='Diabetes pedigree function — a genetic risk score based on family history')),
                ('age', models.IntegerField(help_text='Age in years')),
                ('outcome', models.BooleanField(help_text='True = patient has diabetes, False = patient does not')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['id'],
            },
        ),
    ]
